library(CAGEr)
library(BSgenome.Hsapiens.UCSC.hg19)
pathToInputFiles <- list.files("/home/si14w/gnearline/flu/bowtie_out", pattern="^112213flucap_[A-H]\\.filtered\\.sorted.bam$",full.names = TRUE)
myCAGEset <- new("CAGEset", genomeName="BSgenome.Hsapiens.UCSC.hg19", inputFiles=pathToInputFiles, inputFilesType="bam",sampleLabels=c("A","B","C","D","E","F","G","H"))
getCTSS(myCAGEset)
normalizeTagCount(myCAGEset,method = "none")
#ctss <- CTSSnormalizedTpm(myCAGEset)
ctss_tagCount <- CTSStagCount(myCAGEset)
#write.table(ctss, file=paste("/home/si14w/gnearline/flu/txt/tss_counts.txt",sep=""), quote=FALSE, row.names=FALSE, sep="\t")
write.table(ctss_tagCount, file=paste("/home/si14w/gnearline/flu/txt/tss_counts_raw.txt",sep=""), quote=FALSE, row.names=FALSE, sep="\t")
#exportCTSStoBedGraph(myCAGEset, values = "normalized", oneFile = TRUE)
exportCTSStoBedGraph(myCAGEset, values = "raw", oneFile = FALSE)
